language: node_js
node_js:
  - '10'
cache: npm
install:
  - npm ci && cd src && cd frontend && npm ci && cd .. && cd ..
script:
  - npm run test
  - npm run build
  - node bot/jsSimulationBot.js
  - cd dist && npm pack --dry-run && cd ..
notifications:
  email: false
